classDiagram
    Persona <|-- Cliente
    Persona <|-- Peluquero
    Cliente "1" -->  "0..*" Cita : solicita
    Peluquero "1" -->  "0..*" Cita : atiende
    Local "1" -->  "0..*" Cita : se_realiza_en
    Local "1" -->  "0..*" Peluquero : trabaja_en
    Cita "1" -->  "1..*" Cita_Servicio : incluye
    Servicio "1" -->  "0..*" Cita_Servicio : participa_en

        class Persona {
        +int id_persona pk
        +String nombre
        +String apellido
        +date fecha_nacimiento
        +String telefono
        +String mail
    }

    class Peluquero {
        +verAgenda()
    }

    class Cliente {
        +hash contraseña_cliente
        +String preferencias_estilo
        +solicitarCita()
        +cancelarCita()
    }

    class Servicio{
        +int id_servicio pk
        +String nombre_servicio
        +String descripcion_servicio
        +float precio_servicio
    }

    class Local{
        +int id_local pk
        +String provincia_local
        +String direccion_local
        +String telefono_local
    }
    
    class Cita {
        +int id_cita pk
        +datetime fecha_hora
        +String estado
    }

    class Cita_Servicio{
        +int id_cita_servicio pk
        +float precio_aplicado
    } 
